#!/bin/sh
# Copyright (C) 2006 OpenWrt.org 

START=zz

start() {
	echo "[postinit start]"
	if [ -x /etc/init.d/postinit.ifx ] ; then
		/etc/init.d/postinit.ifx
	fi

	# USB function, including USB FS mounting, Samba, FTP and LPD
	/usr/sbin/usb.sh boot &

	# Web server
	#   replaced by brn-httpd
	#cd /www
	#./httpd
	#cd /

	# DLNA server
	# dlna.sh boot &

	# LAN-WiFi port isolation
	#portiso.sh boot

	# WAN function
	restart_wansvc.sh &

	# LAN function
#	restart_lansvc.sh &

	if [ -x /usr/bin/tftpd ] ; then
		udpsvd -vE 0.0.0.0 69 /usr/bin/tftpd -c /tmp/usb &
	fi

	# refresh neighbors my MAC
	LAN_IP=`umngcli get ip4addr@lan0`
	BR_IF=br-lan
	if [ -n "$LAN_IP" ] ; then
		(arping -A -c 1 -I $BR_IF -s $LAN_IP $LAN_IP ; sleep 3 ; arping -A -c 1 -I $BR_IF -s $LAN_IP $LAN_IP ; sleep 3 ; arping -A -c 1 -I $BR_IF -s $LAN_IP $LAN_IP )&
	fi

	# periodically check PPP connection
	if [ -x /usr/sbin/wan_ppp_admin.sh ] ; then
		/etc/init.d/cron add wan_ppp_chk '* * * * * /usr/sbin/wan_ppp_admin.sh'
	fi

	# periodically check task priority
	if [ -x /etc/init.d/task_prio.sh ] ; then
		/etc/init.d/cron add task_prio_chk '* * * * * /etc/init.d/task_prio.sh check'
	fi


######## sowa ++ #######
	LOG=`/usr/sbin/uboot_env.sh --get --name log2file`
	if [ $LOG == "1" ] ; then
		if [ -x /usr/sbin/console_log.sh ] ; then
			/etc/init.d/cron add console_log_chk '*/1 * * * * /usr/sbin/console_log.sh'
			/bin/ln -sf /tmp/consolelog /tmp/usb/log	
		fi
	fi
######## sowa -- #######


	# update SIP bandwidth in case Giga-WAN
	if [ -x /etc/init.d/brn_sip ] && [ "`umngcli get wan_type@system`" == 2 ] ; then
		/etc/init.d/brn_sip bandwidth 10000 &
	fi

	if [ `/usr/sbin/uboot_env.sh --get --name flashargs | grep -c -e bridge -e mptest -e calibrate -e emi` -ge 1 ] ; then
		echo "######################################################" > /dev/console
		echo "#                                                    #" > /dev/console
		echo "#       WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       #" > /dev/console
		echo "#                                                    #" > /dev/console
		echo "#              NOT NORMAL OPERATION MODE             #" > /dev/console
		echo "#                                                    #" > /dev/console
		echo "######################################################" > /dev/console
	fi

	if [ `grep -c "export CONFIG_UBOOT_CONFIG_DUAL_IMAGE=1" /etc/config.sh` -ge 1 ] ; then
		BOOTID=`/usr/sbin/uboot_env.sh --get --name bootid --force 2>&-`
		echo "######################################################" > /dev/console
		echo "#                                                    #" > /dev/console
		if [ "$BOOTID" != "2" ] ; then
			echo "#              BOOT FROM IMAGE 1                     #" > /dev/console
		else
			echo "#              BOOT FROM IMAGE 2                     #" > /dev/console
		fi
		echo "#                                                    #" > /dev/console
		echo "######################################################" > /dev/console
	fi
	
	# update boot counter
	/usr/sbin/uboot_env.sh --set --name bootnum --value 0

	# periodically check missed task
	if [ -x /usr/sbin/arc-tsk-health-chk.sh ] ; then
		/etc/init.d/cron add tsk_health_chk '* * * * * /usr/sbin/arc-tsk-health-chk.sh'
	fi
}


case "$1" in
	"boot")		start	;;
	"start")	start	;;
#	"stop")		stop	;;
	*)
				echo $0 'boot  - setup and start post-initialization'
				echo $0 'start - start post-initialization'
#				echo $0 'stop  - stop post-initialization'
				;;
esac
