
LIB_MAPI_SRCS = mid_mapi_ccfgsal_wan.c mid_mapi_ccfgsal_vlan.c mid_mapi_ccfgsal_voip.c mid_mapi_ccfgsal_qos.c mid_mapi_ccfgsal_firewall.c mid_mapi_ccfgsal_nat.c mid_mapi_ccfgsal_wlan.c mid_mapi_ccfgsal_util.c
LIB_HDL_SRCS  =
LIB_TEST_SRCS = ccfgsal_cli.c


####################################################################################

include ./mod_make.mk
